
name: Test inside Docker

on:
  pull_request:
    branches: [main]
env:
  SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
  jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t chiptuner:test .

      - name: Run tests inside Docker container
        run: docker run --rm chiptuner:test pytest 
