name: Test inside Docker

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: .env

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t chiptuner:test .

      - name: Run tests inside Docker container
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }} + -e SECRET_KEY=$SECRET_KEY
        run: docker run --rm -e SECRET_KEY=$SECRET_KEY chiptuner:test pytest
        
      - name: Check if SECRET_KEY is non-empty
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }} + -e SECRET_KEY=$SECRET_KEY
        run: |
          if [ -z "$SECRET_KEY" ]; then
            echo "SECRET_KEY is EMPTY"
          else
            echo "SECRET_KEY is NON-EMPTY"
          fi


