name: Django Tests CI

on:
  pull_request:
    branches: [main]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
         env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: docker build --no-cache -t chiptuner:test .

      - name: Run Docker test
         env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: docker run --rm chiptuner:test pytest
