
name: Test inside Docker

on:
  pull_request:
    branches: [main]
env:
  DJANGO_SECRET_KEY: "Uc01YjAgOfzsIqEhzbV4uTE92p7yJ7AntTbO-Ai_dYrnagJe_WZQc0sa0mdgzfVNO2I6cR-zEgNc07x4ioaTQ"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t chiptuner:test .

      - name: Run tests inside Docker container
        run: docker run --rm chiptuner:test pytest 
