name: Django Tests CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build --no-cache -t chiptuner:test .

      - name: Run Docker test
        run: docker run --rm chiptuner:test pytest
