name: Test inside Docker

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t chiptuner:test .

      - name: Run tests inside Docker container
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: docker run --rm -e SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} chiptuner:test pytest

      - name: Debug Secret Key
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: echo "SECRET_KEY=$SECRET_KEY"

